### ISSUE TITLE
Syncing two eyes

### ISSUE THREAD

**Issue by agricolab** [labstreaminglayer/App-PupilLabs#1]
Currently, each eye is an independent LSL stream with irregular sampling rate and two timestamps. Each eye has  a) timestamps as channel, and i assume that's somehow from the hardware or camera, and there are b) LSL timestamps added during relay.
A challenge is how to sync two eyes, as we now have two timestamps. I did not really solve it, but implemented an approach by tweaking the plugin (see https://github.com/translationalneurosurgery/pupil-labs_to_lsl). Essentially, i use a buffer for both eyes, where each stores its last sample received as a ```payload```, and whenever any eye receives a new ```payload```, i am updating the buffer, and sending the buffer (which stores both eyes) with LSL. 

I evaluated it by checking EOG together with pupil diameter changes caused by blinking, and it seems to be sufficiently accurate for my purposes. But this is certainly not the best implementation. 

As i understand it, with ZMQ it is not really guaranteed that the camera timestamps between eye 0 and eye 1 increase monotonic, i.e. i could receive a couple of young samples from eye 0, before i receive the oldest from eye 1. So, maybe there exists another approach to link both eyes already at a lower level, or using a more advanced buffering approach based on the camera timestamps, before relaying with LSL. Yet, this later approach might introduce latency.

**Comment by cboulay** [comment]
I haven't looked closely at the code but the new plugin in #3 puts everything in 1 stream.

**Comment by papr** [comment]
#3 uses Capture's internal pupil data correlation mechanism by extracting the LSL stream data from the already correlated gaze date. In cases where only monocular data is available, the opposing eye data is set to `NaN`.
