### ISSUE TITLE
right plugin for CORE

### ISSUE THREAD

**Issue by jjsapido** [labstreaminglayer/App-PupilLabs#11]
Does the pupilInvisible plugin work with pupilCORE devices?
Or, for CORE, do I have to resort to the pupil capture plugin only? 
There's any other way for direct access and LSL streaming with CORE?

Thanks

**Comment by papr** [comment]
@jjsapido Apologies for the very delayed response!

Pupil Core devices will only work with Pupil Core software (Capture and/or Service). To receive Pupil Core data via LSL you need the Pupil Capture LSL Relay plugin.

The Pupil Invisible Relay does not work with Pupil Core.
