### ISSUE TITLE
Re-adding old pull-requests.

### ISSUE THREAD

**Issue by gmierz** [labstreaminglayer/App-PupilLabs#2]
Hello @cboulay, would you be able to add the old pull requests that you stored for this app? You mentioned that you made a diff of them before the repo was restructured. If it's not possible, that's no problem.

Thanks!

**Comment by cboulay** [comment]
Hmm... I don't know where it is right now... and with my schedule being as it has been lately, I don't see myself getting to this for a few weeks at least.
But seeing as how we didn't end up overwriting the old repo, the old pull request still exists and it's easy to see the requested changes:
https://github.com/sccn/lsl_archived/pull/339/files

Could you make a similar PR against this repo?

**Comment by gmierz** [comment]
@cboulay, thanks for the information and link to the archives! A new PR will be made instead so we don't need to resurrect the old one - it can be deleted if you guys need to.
