### ISSUE TITLE
Add version tag of pylsl/xdf data format.

### ISSUE THREAD

**Issue by gmierz** [labstreaminglayer/App-PupilLabs#6]
I've been using v1.0 of this code and it seems like v2.0 is quite different. I think it might be good to get some sort of "version" number added to the meta-data in case anything else changes in the future so it will be easier to detect changes. One thing that could be done to get this available to the labrecorder is adding a 'meta' channel and sending a single point of data when a consumer is detected.

**Comment by papr** [comment]
Fixed in #7
